name: Latest blog post workflow

on:
  repository_dispatch:
    types: [update_blog_posts]
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://hetong-re4per.com/index.xml"
          max_post_count: 4
