name: GitHub-Profile-3D-Contrib

on:
  schedule: # 09:00 JST == 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: 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
          USERNAME: HeTongRe4per
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
